#!/usr/bin/env bash
set -e
IMAGE_NAME="ldap-proxy"
DOCKER_IMAGE="$DOCKER_REPO/$IMAGE_NAME"
GO_PACKAGE="github.com/fracklen/ldap-proxy"
GIT_REV="$(git rev-parse --short=12 HEAD)"
TAGS="$GIT_REV production"

pushd /tmp
if [ ! -d "/tmp/gockerize" ]; then
    git clone https://github.com/aerofs/gockerize
fi
popd

/tmp/gockerize/gockerize $DOCKER_IMAGE $GO_PACKAGE .

docker push $DOCKER_IMAGE:latest
for tag in $TAGS; do
    docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$tag
    docker push $DOCKER_IMAGE:$tag
done
